export const ProductData = [
  {
    category: "male",
    name: " sweater",
    imageURL: "/event2.png",
    price: "$656",
    make: "wool",
  },
  {
    category: "male",
    name: "jacket",
    imageURL: "/malejac1.png",
    price: "$400",
    make: "cotton",
  },
  {
    category: "male",
    name: "jacket",
    imageURL: "/malejac2.jpg",
    price: "$800",
    make: "polyester",
  },
  {
    category: "kids",
    name: "jacket",
    imageURL: "/kids1.jpg",
    price: "$656",
    make: "wool",
  },
  {
    category: "kids",
    name: "jacket",
    imageURL: "/kids2.jpg",
    price: "$656",
    make: "hybrid",
  },
  {
    category: "female",
    name: "jacket",
    imageURL: "/ladyjac1.png",
    price: "$656",
    make: "wool",
  },
  {
    category: "female",
    name: "shirt",
    imageURL: "/ladyshirt1.png",
    price: "$656",
    make: "cotton",
  },
  {
    category: "female",
    name: "shirt",
    imageURL: "/header.png",
    price: "$656",
    make: "hybrid",
  },
  {
    category: "female",
    name: "sweater",
    imageURL: "/ladysweat1.jpg",
    price: "$656",
    make: "wool",
  },
  {
    category: "male",
    name: "shirt",
    imageURL: "/boyshirt1.jpg",
    price: "$656",
    make: "cotton",
  },
];
